version: 2.1

workflows:
  version: 2.0
  test:
    jobs:
      - test

jobs:
  test:
    docker:
      - image: royvandewater/rust-ci:latest

    steps:
      - checkout

      - run: mkdir ~/results

      - run:
          name: test
          command: cargo test -- -Z unstable-options --format json | cargo2junit > ~/results/junit.xml

      - store_test_results:
          paht: ~/results

  
