version: 2.1

workflows:
  version: 2.0
  test:
    jobs:
      - test

jobs:
  test:
    docker:
      - image: circleci/rust:latest

    steps:
      - checkout

      - run:
          name: test
          command: cargo test
  
